stages:
  - build

build-ozon-app-web:
  stage: build
  image: docker:25
  services:
    - docker:dind

  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - >
      docker build
      --network host
      -f "${CI_PROJECT_DIR}/ozon-app-web/Dockerfile"
      -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      -t "${CI_REGISTRY_IMAGE}:latest"
      "${CI_PROJECT_DIR}/ozon-app-web"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
    - docker push "${CI_REGISTRY_IMAGE}:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "1.0"'
